services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    volumes:
      # Bind mount the hosts current folder to container folder. Allows for syncing changes without rebuild.
      - .:/app

volumes:
  ollama:
