apiVersion: v1
kind: Service
metadata:
  name: ai-playground-ollama
spec:
  type: LoadBalancer
  selector:
    app: ai-playground-ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
